image: node:latest

stages:
  - deploy

deploy_prod:
  stage: deploy
  script:
    - echo "REACT_APP_BASE_URL=https://proposex.netlify.app/api" >> ".env"
    - npm install --force
    - npm install netlify-cli -g
    - npm run build
    - netlify deploy --dir "build" --auth $AUTH_TOKEN --site $SITE_ID_PROD --prod
  only:
    - main

# deploy_develop:
#   stage: deploy
#   script:
#     - echo "REACT_APP_BASE_URL=https://culturenet-apis-develop.netlify.app/.netlify/functions/api" >> ".env"
#     - npm install --legacy-peer-deps
#     - npm install netlify-cli -g
#     - npm run build
#     - netlify deploy --dir "build" --auth $AUTH_TOKEN_RISHI --site $SITE_ID_RISHI --prod
#   only:
#     - develop

# deploy_monil:
#   stage: deploy
#   script:
#     - echo "REACT_APP_BASE_URL=https://culturenet-apis-monil.netlify.app/.netlify/functions/api" >> ".env"
#     - npm install --legacy-peer-deps
#     - npm install netlify-cli -g
#     - npm run build
#     - netlify deploy --dir "build" --auth $AUTH_TOKEN --site $SITE_ID_MONIL --prod
#   only:
#     - main-monil

# deploy_rishi:
#   stage: deploy
#   script:
#     - echo "REACT_APP_BASE_URL=https://culturenet-apis-develop.netlify.app/.netlify/functions/api" >> ".env"
#     - npm install --legacy-peer-deps
#     - npm install netlify-cli -g
#     - npm run build
#     - netlify deploy --dir "build" --auth $AUTH_TOKEN_RISHI --site $SITE_ID_RISHI --prod
#   only:
#     - main-rishi
